spring:
  application:
    name: cloud-common-config
  redis:
    database: 0
    host: 127.0.0.1
    password:
    port: 6379
    config:
      maxTotal: 100
      maxIdle: 10
      maxWaitMillis : 100000

